### ISSUE TITLE
title indicates it's a quiz but it has the console lesson in it

### ISSUE THREAD

**Issue by jonopens** [learn-co-curriculum/js-principles-javascript-principles-quiz#1]
To reproduce:
1. go to https://learn.co/tracks/web-development-immersive-2-0-module-three/new-stuff/principles/javascript-principles-quiz
2. scan the page
3. note there is no quiz
4. note the content is on console, not a quiz

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @jonopens.

We have updated the learn.co track and removed quiz from the title and believe your issue to have been resolved. The repository name will need to stay the same for now to maintain references in our database, but this lesson should now say "JavaScript Principles" on learn.co.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
