### ISSUE TITLE
Lesson Not a Quiz

### ISSUE THREAD

**Issue by Sidhe-is-me** [learn-co-curriculum/js-principles-javascript-principles-quiz#2]
This lesson is named JavaScript Principles Quiz but is actually about logging and the console in JS.

**Comment by kwebster2** [comment]
@cernanb The title of this lesson should be updated

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @Sidhe-is-me and @kwebster2.

We have updated the learn.co track and removed quiz from the title and believe your issue to have been resolved. The repository name will need to stay the same for now to maintain references in our database, but this lesson should now say "JavaScript Principles" on learn.co.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
