### ISSUE TITLE
Quiz

### ISSUE THREAD

**Issue by KhayaDillon** [learn-co-curriculum/js-principles-javascript-principles-quiz#3]
Where is the quiz? Lesson is titled "js-principles-javascript-principles-quiz", but lesson went over console methods.

**Comment by coryjbergquist** [comment]
Agreed, this is mostly repeated content from the JavaScript > Basics > Intro to Debugging lesson. There was no quiz.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @yahyal0v3.

We have updated the learn.co track and removed quiz from the title and believe your issue to have been resolved. The repository name will need to stay the same for now to maintain references in our database, but this lesson should now say "JavaScript Principles" on learn.co.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
